Changed master/slave behavior when starting MySQL
If MySQL was previously a slave, it will continue replicating from the
previous point.  This allows the slave to go down and come back up without
having to reset replication.

diff --git a/mysql b/mysql
--- a/mysql
+++ b/mysql
@@ -740,25 +740,50 @@ mysql_start() {
         # node that is just joining the cluster, and the CRM may have
         # promoted a master before.
         master_host=`echo $OCF_RESKEY_CRM_meta_notify_master_uname|tr -d " "`
-        if [ "$master_host" -a "$master_host" != `uname -n` ]; then
-            ocf_log info "Changing MySQL configuration to replicate from $master_host."
-            set_master $master_host
-            ocf_run $MYSQL $MYSQL_OPTIONS_LOCAL $MYSQL_OPTIONS_REPL \
-                -e 'START SLAVE'
-            if [ $? -ne 0 ]; then
-            ocf_log err "Failed to start slave"
-            return $OCF_ERR_GENERIC
+        master_pref=2
+        if [ "$master_host" ]; then
+            if [ "$master_host" == `uname -n` ]; then
+                ocf_log err "We just started but we are the master!  This shouldn't happen."
+                return $OCF_ERR_GENERIC
+            else
+                # TODO: Check to see if we are replicating from the right master
+                #       Only matters with 3 or more nodes
+                if is_slave; then
+                    ocf_log info "Resuming previous MySQL replication."
+                else
+                    ocf_log info "Changing MySQL configuration to replicate from $master_host."
+                    set_master $master_host
+                    master_pref=1
+                fi
+                ocf_run $MYSQL $MYSQL_OPTIONS_LOCAL $MYSQL_OPTIONS_REPL \
+                    -e 'START SLAVE'
+                if [ $? -ne 0 ]; then
+                    ocf_log err "Failed to start slave"
+                    return $OCF_ERR_GENERIC
+                fi
             fi
+
         else
-            ocf_log info "No MySQL master present, clearing replication state"
-            unset_master
+            if is_slave; then
+                ocf_log info "No MySQL master present, resuming last know slave replication"
+                ocf_run $MYSQL $MYSQL_OPTIONS_LOCAL $MYSQL_OPTIONS_REPL \
+                    -e 'START SLAVE'
+                if [ $? -ne 0 ]; then
+                    ocf_log err "Failed to start slave"
+                    return $OCF_ERR_GENERIC
+                fi
+            else
+                ocf_log info "No MySQL master present, clearing replication state"
+                unset_master
+                master_pref=3
+            fi
         fi
 
         # We also need to set a master preference, otherwise Pacemaker
         # won't ever promote us in the absence of any explicit
         # preference set by the administrator. We choose a low
         # greater-than-zero preference.
-        $CRM_MASTER -v 1
+        $CRM_MASTER -v $master_pref
     fi
 
     ocf_log info "MySQL started"
